### ISSUE TITLE
route -n command cannot get parsed

### ISSUE THREAD

**Issue by fjhunter** [FGRibreau/network-config#35]
When the Gateway is determined by the `route -n` command the regex doesn`t match anymore.

route -n output: `0.0.0.0         192.168.1.1     0.0.0.0         UG    0      0        0 enp1s0`

route output: `default         192.168.1.1     0.0.0.0         UG    0      0        0 enp1s0`

As you can see `default` changes to `0.0.0.0`.

A better way do determine the gateway would be by adding `| awk '$4 == "UG" {print $2}'` At the end of the route command. This way you get the default gateway directly and with both commands with and without `-n`

**Comment by FGRibreau** [comment]
Thanks for your feedback, instead of adding a dependency requirement on `awk`, I would prefer an improvement on the parse() function https://github.com/FGRibreau/network-config/blob/2c135e4d6b14d0b83bb6fa3a53e809f2ba7403a7/src/ifconfig.interfaces.js#L50 along with added non-regression tests.
I will accept a PR for that :+1:

**Comment by FGRibreau** [comment]
Fixed by https://github.com/FGRibreau/network-config/pull/39
